### ISSUE TITLE
Window being leaked

### ISSUE THREAD

**Issue by MinceMan** [mariosangiorgio/RateMyApp#23]
If the device is rotated while the rate dialog is up the window for that activity will be leaked. I would recommend holding onto the context as a weak reference.

```
04-15 13:37:45.635  22119-22119/com.fake E/WindowManager﹕ Activity com.fake.activity.FakeActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{44de2398 V.E..... R....... 0,0-684,390} that was originally added here
    android.view.WindowLeaked: Activity com.fake.activity.FakeActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{44de2398 V.E..... R....... 0,0-684,390} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:394)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:239)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
            at android.app.Dialog.show(Dialog.java:286)
            at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
            at com.mariosangiorgio.ratemyapp.RateMyApp.showDialog(RateMyApp.java:91)
            at com.mariosangiorgio.ratemyapp.RateMyApp.appLaunched(RateMyApp.java:51)
            at com.fake.activity.FakeActivity.onCreate(FakeActivity.java:121)
            at android.app.Activity.performCreate(Activity.java:5195)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2473)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574)
            at android.app.ActivityThread.access$600(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1413)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:5789)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:843)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mariosangiorgio** [comment]
I'm going to have a look at it. It would be great if I were able to write unit tests for errors like this. Do you have any idea of whether it is possible?

**Comment by mariosangiorgio** [comment]
Can you please explain me what I should hold onto the context as a weak reference?

I found another possibile fix to this issue but it is a bit convoluted. It involves returning a reference to the dialog and manually dismissing it in the `onPause` method.

**Comment by MinceMan** [comment]
I don't know about finding problems like this with testing but testing can for sure be put into this library. The key is that the testing goes into a sample app instead of the library itself. Check out my open source project SectionCursorAdapter https://github.com/twotoasters/SectionCursorAdapter and let me know if you have any problems.

**Comment by MinceMan** [comment]
The weak reference is pretty easy

``` java
private final WeakReference<Context> contextRef;
// Then in the constructor...
contextRef = new WeakReference<Context>(context);
```

Then when you want to use the context you need to check if you still have a reference to it as the reference could disappear if the system sees that it can garbage collect. This is a good this as your app will have already destroyed your activity and there will no longer be a leak. 

``` java
public void showDialog() {
    if (contextRef.get() != null) {
```

**Comment by mariosangiorgio** [comment]
If I understand well in that way I will not be able to go on with the task if the screen gets rotated. Am I right? That does not seem the best option to me.

I created an `experiments` branch where I am trying to use fragments that will stay alive even after a rotation but I am having issues with the `FragmentManager`. The instance I have at the beginning goes away when the activity go away and I am not sure if/how I can get the new one from the classes I created earlier on the previous context.

**Comment by MinceMan** [comment]
I'll check out your branch. I have a lot of experience with this. We'll be
able to reshow it without holding a hard reference as the activity will let
the fragment manager handle everything.

**Comment by mariosangiorgio** [comment]
I think that the root cause of the issue is that at the moment I hold a reference of `FragmentManager` in `ShowDialogAction`. That reference is created in the context of the first activity.

**Comment by mariosangiorgio** [comment]
I think I solved the issue in [this commit](https://github.com/mariosangiorgio/RateMyApp/commit/10c8b62d33e0970666afe8aae9e89ba846972431). I'm still not totally satisfied because it feels a bit more an hack than a clean solution.

Would you mind testing if it works and having a look at the code to see if there is a better way to solve the issue?

**Comment by MinceMan** [comment]
I should be able to look at it over the weekend if that works for you.

**Comment by mariosangiorgio** [comment]
Brilliant! There is absolutely no urgency. Thanks for helping me improving the project.

**Comment by MinceMan** [comment]
Hey Mario, I have two pull requests on my fork if you wanna check them out https://github.com/chris2toasters/RateMyApp/pulls. They are in order. I didn't send them to you because I didn't want to go off your latest experiments commit. If there is something in that latest commit you wanted, just point me to it and I'll add it in. Overall I think the movement over to the fragments was a really good idea. I don't know if you were still having a problem with rotation but it isn't a problem anymore.

**Comment by MinceMan** [comment]
Also if you like this I can update the readme. Feel free to be very critical and dig in or ask any questions if you don't understand why I did something or how it works.

**Comment by mariosangiorgio** [comment]
Thanks for your commits, they are a great contribution!

I have a couple of doubts about how things works. I am going to add comments directly on the pull requests. I think it would be easier for both to discuss them with a clear reference to the lines of code.
